### ISSUE TITLE
Running the contributed command: 'psi-header.insertFileHeader' failed.

### ISSUE THREAD

**Issue by Timecrash** [davidquinn/psi-header#17]
VS Code version: 1.57.0
Extension version: 1.15.2
OS: Windows (using the Remote SSH extension for an Oracle Linux workspace)

I used this extension without issue as of a couple months ago, however using it now results in this error:

`Running the contributed command: 'psi-header.insertFileHeader' failed.`

Nothing changed on my side apart from updating VS Code. I get this error both on my Linux workspace and the normal Windows environment.

**Comment by davidquinn** [comment]
I have seen this error in the past and it is usually either something to do with a problem during in VSC itself during an upgrade or there is a conflict with another extension. The former is the more common.

It has reportedly been fixed by uninstalling the extension, restart VSC then reinstall the extension. But you may want to backup your settings before hand just in they are wiped when you uninstall the extension (sorry, I don't recall off the top of my head if they get removed).

If that doesn't fix it, then let me know and I will try to find in my history what extension previously caused problems - or let me know what other extensions you have installed.

Regards
D

**Comment by davidquinn** [comment]
After some testing, it looks like this only occurs in the following scenario:
1. Create a new File (via File->New)
2. Use the keyboard shortcut Ctrl-H, Ctrl-H to add a header before the file has ever been saved to disk.

However, it works fine if you do the following (in this instance the auto-save settings are activated):
1. Create a new File (via File->New)
2. Save the file - the file is saved and the header is correctly inserted.

Also, once the file has been saved to disk, even the keyboard shortcut seems to work fine.

This suggests to me that something has changed in the way VSCode deals with files that have not yet been persisted to disk. I will investigate this further but in the meantime I hope the above will help you to get on with your work.

Can you try the above and confirm if that works in your environment?

Regards
David

**Comment by Timecrash** [comment]
Hi, David,

I can confirm both the keyboard shortcut and the command palette works once I save the file. Thanks! Would you like me to close the issue, or keep it open until you figure out what's causing the problem?

**Comment by davidquinn** [comment]
Great, thanks Matt for getting back to me. 

Leave it open and I will get to the bottom of what is causing it.
