### ISSUE TITLE
Do not skip empty lines during replace

### ISSUE THREAD

**Issue by dlech** [davidquinn/psi-header#36]
I have set up a project to automatically update the copyright on save. However, I have found a problem for vendored files that have an additional copyright. 

Example:

```python
# SPDX-License-Identifier: MIT
# Copyright (c) 2022 Me

# This file is based on https://example.com
# Copyright (c) 2019 Someone Else
```

Since the replace function [skips empty lines](https://github.com/davidquinn/psi-header/blob/20eb8369040fbc1d4377b93db60beea74eb057f9/src/changesTrackingController.ts#L167), it happily replaces `Copyright (c) 2019 Someone Else` with `Copyright (c) 2019-2020 Me`, which is, of course, not desirable.

To work around this, we have to add code between the first comment block and the second comment block.

**Comment by davidquinn** [comment]
The skipping of empty lines during replace was intentional and based on requests from users early on. I can't see an easy way to deal with it short of adding a config option to not skip empty lines. 

The issue here is that both lines start `# Copyright` which I am guessing is what your configuration was set up to identify as a replaceable line. So an alternative approach would be to ensure the vendor copyright does not start the same. For example:

```
# This file is based on https://example.com. Copyright (c) 2019 Someone Else
```

Does this work for you?

Regards
David

**Comment by dlech** [comment]
I suppose that is a reasonable workaround (although the URL is usually very long and we wouldn't want to put something after it, but changing the line to `Original copyright ...` or something like that could work). 

In C code, as a workaround, I was able to use `//` in the header and added `/***/` as a delimiter to mark the end of the header.

**Comment by dlech** [comment]
On the other hand, one of the main benefits of this extension is that it makes it so you don't have to think about the header at all (after initial setup). And the workarounds require you to think about the rules of the header implementation and how to work around it - and if you don't think about it, you accidentally commit wrong changes to someone else's copyright.

**Comment by davidquinn** [comment]
I get what you are saying about having to think and it is a good point. 

Your suggestion of not using Compact Mode solves the problem. I didn't suggest that before because people get so attached to their favoured comment formatting! But unfortunately it is really the use of Compact Mode which causes the problem because it makes it far more difficult for the extension to detect beginning and end of header.

I guess I could try and add a configuration setting that would ignore comments after the first blank line in compact mode, but I worry that the problem is very edge case and I think it would raise many more problems (e.g. where licence text is being inserted into the header, or where fixed width is used).

So on balance, I would prefer not to do anything with this, but happy to discuss further.

Regards
D
