### ISSUE TITLE
the "Last Modified: " doesnt update when the dart file changed, 

### ISSUE THREAD

**Issue by zhangwb1996** [davidquinn/psi-header#49]
i use `psi-header1.21.0` with `vscode1.75` and config `./vscode/settings.json`  instead of the global `settings.json`.
is there any errors in my configuration
```
{
  "psi-header.config": {
    "forceToTop": true,
    "blankLinesAfter": 1,
    "spacesBetweenYears": false,
    "license": "MIT",
    "author": "**********",
    "authorEmail": "**********",
    "creationDateZero": "asIs",
    "autoHeader": "autoSave",
  },
  "psi-header.changes-tracking": {
    "isActive": true,
    "autoHeader": "autoSave",
    "enforceHeader": true,
    "modAuthor": "Modified By: ",
    "modDate": "Last Modified: ",
    "exclude": [
      "markdown",
      "json",
      "jsonc",
      "shellscript",
    ],
    "excludeGlob": [
      "**/*/*.bak",
      "**/*/*.yaml",
      "**/*/.gitignore",
    ],
    "replace": [
      "File: ",
      "Project: ",
      "HISTORY:",
    ],
    "updateLicenseVariables": false
  },
  "psi-header.lang-config": [
    {
      "language": "dart",
      "begin": "///",
      "prefix": "/// ",
      "suffix": "",
      "lineLength": 80,
      "end": "///",
      "forceToTop": true,
      "blankLinesAfter": 1,
      "beforeHeader": [],
      "afterHeader": [],
      "rootDirFileName": "pubspec.yaml",
    }
  ],
  "psi-header.templates": [
    {
      "language": "*",
      "template": [
        "File: <<filerelativepath>>",
        "Project: <<projectname>>",
        "",
        "Created Date: <<filecreated('dddd, YYYY-MM-DD h:mm:ss a')>>",
        "Author: <<author>> (<<authorEmail>>) ",
        "-----",
        "Last Modified: <<dateformat('dddd, YYYY-MM-DD h:mm:ss a')>>",
        "Modified By: <<author>> (<<authorEmail>>)",
        "-----",
        "Copyright (c) <<yeartoyear(fc, now)>>",
        "-----",
        "HISTORY:",
        "Date      \tBy\tComments",
        "----------\t---\t---------------------------------------------------------"
      ],
      "changeLogCaption": "HISTORY:",
      "changeLogHeaderLineCount": 2,
      "changeLogEntryTemplate": [
        "",
        "<<dateformat(DD-MM-YYYY)>>\t<<initials>>\t"
      ],
    }
  ],
}
```
this is the result, but when the dart file changed, the `Last Modified: `  update nothing
```
///
/// File: *****
/// Project: ******
///
/// Created Date: Thursday, 2023-02-02 11:14:33 pm
/// Author: ******* (*************)
/// -----
/// Last Modified: Monday, 2023-02-06 12:42:39 am
/// Modified By: ********* (********)
/// -----
/// Copyright (c) 2023
/// -----
/// HISTORY:
/// Date      	By	Comments
/// ----------	---	---------------------------------------------------------
///
```

**Comment by davidquinn** [comment]
Is it Modified By (as per the title) or Last Modified (as per the message) that is not working?

**Comment by zhangwb1996** [comment]
> Is it Modified By (as per the title) or Last Modified (as per the message) that is not working?

can not update Last Modified: when file updated. sry, that is a copyed mistake

**Comment by davidquinn** [comment]
OK, I can't see anything obviously wrong so I will have to try and debug it to see what might be going on. But when you say that the Last Modified line is not updated, I can see that it has a later date/time than the Created Date.

Are you modifying the file in VSC, or are you doing it externally and expecting it to update in VSC? 

Are you sure it is not updating (because the date is clearly later than the created date)?

Do you have this file open in the editor when you are saving, or is it being saved via "Save All"?

D

**Comment by zhangwb1996** [comment]
> OK, I can't see anything obviously wrong so I will have to try and debug it to see what might be going on. But when you say that the Last Modified line is not updated, I can see that it has a later date/time than the Created Date.
> 
> Are you modifying the file in VSC, or are you doing it externally and expecting it to update in VSC?
> 
> Are you sure it is not updating (because the date is clearly later than the created date)?
> 
> Do you have this file open in the editor when you are saving, or is it being saved via "Save All"?
> 
> D

> if there is no psi-header line  or i remove all the existed psi-header lines in this file, this "Last Modified: " line can be created successfully when i edit and save this file. 
>
> But if there are psi-header lines, this "Last Modified: " update nothing when i edit and save this file in VSC

**Comment by davidquinn** [comment]
OK. Thanks for the updated info that helped. I have worked it out - the problem is that the `begin`, `prefix` and `end` in the `lang-config` are all exactly the same coupled with the fact that you have blank lines within the template. So the extension is reading the file to find where the header starts (i.e. the first line where line = prefix), then it keeps reading the file until it gets to a line that matches the `suffix` which in your case is line 4. 

So either you need to make sure that there is something on line 4 of your template (e.g. '-----') or make sure that the `suffix` is different to the `prefix`. Alternatively, take a look in the readme documentation at "Compact Mode".

Regards
D

**Comment by davidquinn** [comment]
OK, not a problem.
