### ISSUE TITLE
`File name` cannot be automatically updated after the file is renamed.

### ISSUE THREAD

**Issue by MambaWong** [davidquinn/psi-header#55]

**Comment by davidquinn** [comment]
It does work. However, VSC does not trigger a change event at the point the filename is changed - only when changes *_within_* the file are saved. So, next time you make a change in the file and save it (even just add and remove a space), the new filename will be picked up - assuming you have configured the extension to do this.

There is now an onFilesRenamed event that I can try to subscribe to, but it is triggered when any files or directories are renamed - not when the file in the editor is renamed - and it depends on how the file was renamed as to whether it triggers the event or not. I need to look at whether this is feasible.

**Comment by davidquinn** [comment]
It does not appear to be feasible due to the way VSCode Extensions work. This extension works by recognising that the file in the editor has changed, but the onFilesRenamed event works by looking for filename changes across any file/directory so it does not correlate to the file in the editor.

Closing this as there doesn't appear to be a way to do it.
