### ISSUE TITLE
Could you provide a template for all language(as much as possible) by default

### ISSUE THREAD

**Issue by eromoe** [davidquinn/psi-header#62]
Current default failed on many extensions like  markdown, json, yaml, cmd ... 
Have to add setting for each everytime manually. 
Maybe we can create a issue to collect the default template for each language .

**Comment by davidquinn** [comment]
I am not sure what you are trying to achieve because you only *__need__* a single `template`. You can create different templates for different languages but you usually don't need to.

Do you mean `lang-config` or do you mean the ability to exclude specific file types? Most of the file types you mention are ones that are commonly (but not always) excluded via the `exclude` or `excludeGlob` settings in `changes-tracking` - refer to the documentation for an example for this. 

And what do you mean by"Have to add setting for each everytime manually"? If you add them to VSCode's global settings you only have to add them once.

If you mean `lang-config`, the extension does include defaults for a small selection of languages, but there are multiple ways to configure many of the languages that also depend on other settings you make in this extension (e.g. using `compactMode`). I am not averse to people submitting pull requests to add other languages, but only if that does not break the existing configuration for other users.

Regards
D

**Comment by eromoe** [comment]
Understand, I just mean a new user need add templates or set exclude by themself, it would be handy if there are defaults `lang-config` for all language.

**Comment by davidquinn** [comment]
OK, so language templates. I did actually add a default exclusions list in an earlier release but had to remove it again as I got too many complaints about certain file types "no longer working". There are very few file types that absolutely do not allow comments (even Markdown has hacky ways of allowing them). So the easiest thing to do is to allow users to set their own exclusion list.

As for default language configs, there are a small number of default languages catered for and it does default to the ubiquitous `/* ... */` which covers quite a few languages. But I am happy to accept pull requests or add other languages as well that do not break functionality for existing users. At the moment, in addition to the overall default, there are defaults for: swift, Lua, pearl, ruby, vb, Clojure, python, xml, html and Matlab.

D
